// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL4ZkZNYU75u2ljhAWE5nQ4bI0ZTTQqRc',
    appId: '1:53409692171:web:9f0b0647505d7ebc07a50e',
    messagingSenderId: '53409692171',
    projectId: 'musicart-753ec',
    authDomain: 'musicart-753ec.firebaseapp.com',
    storageBucket: 'musicart-753ec.appspot.com',
    measurementId: 'G-YB1LRNFWFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc6LDCAKL0n4E4R6Fe6kaKhJy7bzCWgcc',
    appId: '1:53409692171:android:7a1bd6a4ef07de7e07a50e',
    messagingSenderId: '53409692171',
    projectId: 'musicart-753ec',
    storageBucket: 'musicart-753ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLusFTQbFORgFExgfo_PWucw3tOtmp01A',
    appId: '1:53409692171:ios:f37fbdb5455de62807a50e',
    messagingSenderId: '53409692171',
    projectId: 'musicart-753ec',
    storageBucket: 'musicart-753ec.appspot.com',
    iosClientId: '53409692171-qrcai1clae1s93qnjjdb78t9dmfl2t08.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLusFTQbFORgFExgfo_PWucw3tOtmp01A',
    appId: '1:53409692171:ios:f37fbdb5455de62807a50e',
    messagingSenderId: '53409692171',
    projectId: 'musicart-753ec',
    storageBucket: 'musicart-753ec.appspot.com',
    iosClientId: '53409692171-qrcai1clae1s93qnjjdb78t9dmfl2t08.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicart',
  );
}
